# Generated by Django 5.1 on 2024-08-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
